name:                aoc-moribund-aardvark
version:             0.1.0.0
github:              "alyssaruth/aoc-moribund-aardvark"
license:             BSD3
author:              "Alyssa Burlton"
maintainer:          "example@example.com"
copyright:           "2024 Alyssa Burlton"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/AdventOfCode2022#readme>

dependencies:
- base >= 4.7 && < 5
- advent-of-code-api >= 0.2.8
- text
- dotenv
- transformers
- trifecta
- directory
- text-format
- containers
- combinatorial
- linear
- lens
- split
- mtl
- safe
- finite-typelits
- monad-loops
- monad-extras
- PSQueue
- parser-combinators
- parsers
- regex-tdfa

library:
  source-dirs: src

executables:
  aoc-moribund-aardvark-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc-moribund-aardvark

tests:
  aoc-moribund-aardvark-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc-moribund-aardvark
